### ISSUE TITLE
Compound Variabler with nested & mixed components

### ISSUE THREAD

**Issue by arialcrime** [mekkablue/Glyphs-Scripts#183] opened 2020-02-05 09:46 UTC
I have a file where the dot glyph contains bracket layers. The dieresis is constructed of 2 dot components. When applying Compound Variabler it generates the bracket layers twice in the dieresis glyph. Furthermore, glyphs using the dieresis glyph do not get the layers from the dot component at all. 

In mixed components which only use the dot once get the layers, but the reinterpolation of the path does not work properly.

I attached 2 files to illustrate the issue.

[Compound Variabler Issue.zip](https://github.com/mekkablue/Glyphs-Scripts/files/4158647/Compound.Variabler.Issue.zip)

**Comment by arialcrime** [comment] 2020-02-10 09:19
Thanks for the quick fix concerning the double layers. 

Looks like the script still does not work properly with mixed components (the C glyph in the attached file). Furthermore, component glyphs with a nested component (the D and E glyph in the attached file) do not get the bracket layers at all.

Hope that helps!

**Comment by mekkablue** [comment] 2020-02-24 02:25
* Cannot reproduce with C anymore. Must have been fixed in the latest version.
* for D and E, I added the new option *catch all nested components* which simply reruns the whole process as often as the nestings go deep

**Closed by mekkablue** 2020-02-24 02:25 UTC
