### ISSUE TITLE
Steal Kerning Indesign

### ISSUE THREAD

**Issue by fizzybubbele** [mekkablue/Glyphs-Scripts#95] opened 2016-03-16 14:00 UTC
Dear Mekkablue,

when I try your script this error appears in the macro-panel:

Start
Traceback (most recent call last):
  File "Steal kerning from InDesign.py", line 81, in <module>
    Glyphs.clearLog()
  File "GlyphsApp/__init__.py", line 535, in __ClearLog
    
AttributeError: 'GSMenu' object has no attribute 'clearConsole'
End

Please, can you help me? Thank you.

**Comment by mekkablue** [comment] 2016-03-16 14:51
Which version of Glyphs, the OS, InDesign?

**Comment by fizzybubbele** [comment] 2016-03-16 15:15
Thanks. Here are the versions: Glyphs  2.3b, OS El Capitan 10.11, Indesign CC 2015.

**Comment by schriftlabor** [comment] 2016-03-16 17:26
I cannot reproduce it in the latest beta, but I get a different error which needs to be fixed in the app. Perhaps update the modules. Or run it again with the latest stable version.

**Comment by fizzybubbele** [comment] 2016-03-17 12:28
Thanks for your support. I tried to run the script with latest stable version (2.2.2) and now it's popping up this message: 75:80: syntax error: Expected end of line but found identifier. (-2741)

**Comment by mekkablue** [comment] 2016-03-23 08:57
Cannot reproduce it. Have you set up the InDesign document the way it is described?

**Comment by fizzybubbele** [comment] 2016-03-23 09:28
Yes, I did so and I figured out that it still works with Indesign CS6. I recently updated all my software versions (Glyphs 2.2.2 and IndesignCC2015) on my new mac and the macro panel shows more errors: 

AppleScript Error:
85:90: syntax error: Expected end of line but found identifier. (-2741)

AppleScript Error:
79:84: syntax error: Expected end of line but found identifier. (-2741)

AppleScript Error:
41:57: execution error: Can’t get application "InDesign". (-1728)

AppleScript Error:
75:80: syntax error: Expected end of line but found identifier. (-2741)

It’s no big issue if you can’t reproduce it.

**Comment by schriftlabor** [comment] 2016-03-23 15:57
That means that the script could not find InDesign. Do you have the latest version of the scripts?

**Comment by fizzybubbele** [comment] 2016-03-25 13:02
Yes, I have the latest versions of all scripts – I absolutely updated everything.

**Comment by schriftlabor** [comment] 2016-03-29 06:46
Then you will Need To edit the script, I am afraid. Type 

tell app "InDesign"
end 

…in AppleScript Editor and compile, the editor will change the code, then search and replace the code in the .py file accordingly.

**Comment by fizzybubbele** [comment] 2016-03-29 08:36
Thank you! It works very well.

**Closed** 2016-03-30 11:46 UTC
