### ISSUE TITLE
Steal Metrics

### ISSUE THREAD

**Issue by elenage** [mekkablue/Glyphs-Scripts#212] opened 2021-01-14 16:39 UTC
Copies LSB ok, but with RSB it is adding new value (the one you copy from another master/font) of RSB to the existing one. So if it was: LSB=100, RSB=100, when copy LSB=50 and RSB=50 from another master, it sets LSB to 50 but RSB to 150.

**Comment by mekkablue** [comment] 2021-02-15 10:13
Researching, but seems to be related to a bug in the app. Current workaround: click _Transfer_ multiple times.

**Comment by elenage** [comment] 2021-02-19 19:44
It looks like **it is** the app issue. I've noticed that _sometimes_ when you are trying to change a sidebearing (in my case right sidebearing) for a letter that has a metric key, instead of deleted the metric key and assigning the sidebearing you are entering, it starts adding the number you've just entered to the metric key value and keeps doing it.
For example, "m" has a right metric key "n(20)", I want to change it to 30 (no metric key). When entering 30 in the right sidebearing field, it sets it to 50, I delete 50 and enter 30 again, it sets the sidebearing to 80, then to 110 etc.
I wanted to record the video but it doesn't always happen.

**Comment by schriftgestalt** [comment] 2021-02-19 20:07
We have seen that issue once in a while but I was not able to reproduce it.

**Comment by mekkablue** [comment] 2021-04-30 18:34
We have opened an issue in the Glyphs.app repo. Closing this issue here.

**Closed by mekkablue** 2021-04-30 18:34 UTC
