### ISSUE TITLE
Sample String Maker not adding lines

### ISSUE THREAD

**Issue by chofrosubo** [mekkablue/Glyphs-Scripts#227] opened 2021-04-23 08:35 UTC
Glyphs Version 2.6.7 (1356)

![Bildschirmfoto 2021-04-23 um 10 18 03](https://user-images.githubusercontent.com/16613889/115843864-95da8680-a41f-11eb-8b38-c3b6980ad8b0.png)
<img width="725" alt="Bildschirmfoto 2021-04-23 um 10 15 22" src="https://user-images.githubusercontent.com/16613889/115843882-9a06a400-a41f-11eb-812c-0f9c157493de.png">

**Comment by mekkablue** [comment] 2021-04-30 18:52
Works for me in Version 2.6.7 (1356), I believe even with the same font you tried:

![image](https://user-images.githubusercontent.com/1103103/116740573-7df19c80-a9f5-11eb-8315-b1e8d85cbd5a.png)

**Comment by etunni** [comment] 2021-04-30 21:33
Hi Mekka,

Don’t work for me —same version and build—

Saludos,
Eduardo

**Comment by mekkablue** [comment] 2021-05-04 14:06
@etunni Which options do you have enabled? Can you post a screenshot of the window?

**Comment by etunni** [comment] 2021-05-04 15:58
Hi Rainer,

I attached a screenshot.

Saludos,
Eduardo Tunni

**Comment by etunni** [comment] 2021-05-05 15:40
![Screen Shot 2021-04-30 at 18 31 24](https://user-images.githubusercontent.com/5973399/117168994-0fb72c00-ad9f-11eb-8f4d-9b03273217a6.png)

**Comment by mekkablue** [comment] 2021-05-06 23:52
As far as I can see, it works…?

The text in the macro window says it added 240 lines to the sample texts, and the first one is `HOOHA.noon`, for the kerning pair `A`-`period`. The `list index out of range` messages is probably caused by a plug-in, not by the Sample String Maker script.

**Comment by etunni** [comment] 2021-05-07 12:17
Hi Rainer,
I restarted Glyphs 3.6.7 (1356) without plugins but don’t worked, a single line was added.
Saludos, Eduardo
![Screen Shot 2021-05-07 at 09 09 20](https://user-images.githubusercontent.com/5973399/117448081-ace7a100-af14-11eb-92c1-c7acddf095c7.png)

**Comment by mekkablue** [comment] 2021-05-09 08:51
Cannot reproduce. The lines are added to _Edit > Select Sample Text_ or _Glyphs > Preferences > Sample Strings_ under `### CUSTOM KERN STRING ###`:

![image](https://user-images.githubusercontent.com/1103103/117565910-15b94f80-b0b4-11eb-907e-ea104e96f089.png)

Maybe a misunderstanding in usage? It will open the first line in Edit view. In order to go to the second line, you need to choose _Edit > Other > Select Next Sample String_ (I recommend setting a keyboard shortcut).

**Comment by etunni** [comment] 2021-05-09 12:36
> Maybe a misunderstanding in usage?
Yes Rainer! you discovered my ignorance at this point
Thanks :)

**Comment by RafalBuchner** [comment] 2021-06-08 09:43
Looks like something solved, I'm closing this issue

**Closed by RafalBuchner** 2021-06-08 09:43 UTC
